services:

  frontend:

    build: ./frontend

    container_name: employee-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - employee-network


  backend:

    build: ./employee-api

    container_name: employee-backend

    expose:
      - "5000"

    environment:

      DB_HOST: ${DB_HOST}

      DB_USER: ${DB_USER}

      DB_PASSWORD: ${DB_PASSWORD}

      DB_NAME: ${DB_NAME}

      DB_PORT: ${DB_PORT}

    depends_on:
      - database

    networks:
      - employee-network


  database:

    image: mysql:8.0

    container_name: employee-database

    environment:

      MYSQL_ROOT_PASSWORD: rootpassword

      MYSQL_DATABASE: employee_db

    volumes:

      - mysql-data:/var/lib/mysql

      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - employee-network


networks:

  employee-network:


volumes:

  mysql-data:
